### ISSUE TITLE
Readme examples deadlock

### ISSUE THREAD

**Issue by clbarnes** [tardyp/txrequests#8]
Python 3.6, Ubuntu 16.04

I've just added `main()` at the bottom of both code samples in the README and neither of them print anything: on keyboard interrupt it seems they're waiting at a `lock.acquire`. The serial version works fine.

**Comment by tardyp** [comment]
You need to run main() inside the reactor:
```
from twisted.internet import task, defer

task.react(main)
```
http://twistedmatrix.com/documents/current/core/howto/defer.html
